imagePullSecret: artifactory

replicaCount: 1

image:
  registry: docker-live
  repository: sergeydz/release-promotion-sample
  tag: 1.0.5
  pullPolicy: Always

container:
  port: 8000

service: 
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 300Mi

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths:
    - /
  